### ISSUE TITLE
Azure Cloud Connection refused

### ISSUE THREAD

**Issue by l0gicforce** [arduino/ArduinoCloudProviderExamples#3] opened 2019-03-25 08:51 UTC
Hi,

I am trying to connect an Arduino MKR GSM 1400 to the Azure Cloud, exactly following the tutorial. However I get an connection refused error (.-2). 
Has anyone experienced this as well?

According to Microsoft support the error is caused due to no matching certificate provided (none or not matching). No modifications of the code besides Arduino secrets.
The following attempts were done to solve this problem but no success:

-  Redoing the whole tutorial
-  Verifying the thumbprint stored at the IoT Hub (Device Twin)
-  Regenerate public certificate only (and recreating Device on IoT Hub)
-  SIM card and Arduino are functional. Pinging other sites works. Using the SDK to connect to IoT Hub works as well.

Thanks and best regards
Jason

**Comment by sandeepmistry** [comment] 2019-03-26 19:56
Hi @l0gicforce,

Would you be able to try again, but this time change the `GSM gsmAccess;` line in the sketch to `GSM gsmAccess(true);` and provide the output of the Serial Monitor here. Thanks.

**Comment by l0gicforce** [comment] 2019-03-27 09:35
Hi @sandeepmistry,
Here is the full serial output.
Thanks for your quick reply

```
Attempting to connect to the cellular network
⸮AT

OK
AT+IPR=921600

OK
AT

OK
AT+UPSV=3

OK
AT+CPIN?

ERROR
AT+CPIN?

ERROR
AT+CPIN?

ERROR
AT+CPIN?

ERROR
AT+CPIN?

ERROR
AT+CPIN?

ERROR
AT+CPIN?

ERROR
AT+CPIN?

+CPIN: READY

OK
AT+CMGF=1

OK
AT+UDCONF=1,1

OK
AT+CTZU=1

OK
AT+UDTMFD=1,2

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,0

OK
AT+CREG?

+CREG: 0,1

OK
AT+UCALLSTAT=1

OK
AT+CGATT=1

OK
AT+UPSD=0,1,"internet.t-mobile.de"

OK
AT+UPSD=0,6,3

OK
AT+UPSD=0,2,"t-mobile"

OK
AT+UPSD=0,3,"tm"

OK
AT+UPSD=0,7,"0.0.0.0"

OK
AT+UPSDA=0,3

OK
AT+UPSND=0,8

+UPSND: 0,8,1

OK
You're connected to the cellular network

Attempting to MQTT broker: IoTHubTestKB001.azure-devices.net 
AT+USOCR=6

+USOCR: 0

OK
AT+USOCO=0,"IoTHubTestKB001.azure-devices.net",8883

OK
AT+CCLK?

+CCLK: "04/01/01,00:03:15+00"

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USOWR=0,238,"16030100E9010000E503030000000045F4654817CBA0161BEFBDED35CC825C159D88B332F9C2EFB0B6EAE500005ACCA9CCA8C02BC02FC02CC030C0ACC0ADC0AEC0AFC023C027C024C028C009C013C00AC014C02DC031C02EC032C025C029C026C02AC004C00EC005C00F009C009DC09CC09DC0A0C0A1003C003D002F0035C008C012C003C00D000A01000062FF01000100000000260024000021496F54487562546573744B423030312E617A7572652D646576696365732E6E65740001000101000D001600140403030305030603020304010301050106010201000A000A0008001700180019001D000B00020100"

+USOWR: 0,238

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USORD=0,512

+USORD: 0,0,""

OK

+UUSORD: 0,2920
AT+USORD=0,512

+USORD: 0,512,"16030310960200004D03035C9B41E9F41B67CE2EE4CC993A369FD3EED85033303BF1D65A6D64876EF09092201F2D0000C885CB2525AE6442CCA94345C7604D9FA7AA4953DC4C3AA2AE6EF9C5C027000005FF010001000B000EB4000EB10008F3308208EF308206D7A0030201020213200005A32E554767A5DAA83A2800000005A32E300D06092A864886F70D01010B050030818B310B3009060355040613025553311330110603550408130A57617368696E67746F6E3110300E060355040713075265646D6F6E64311E301C060355040A13154D6963726F736F667420436F72706F726174696F6E31153013060355040B130C4D6963726F736F6674204954311E301C060355040313154D6963726F736F667420495420544C532043412032301E170D3139303331343134343630385A170D3231303331343134343630385A301E311C301A06035504030C132A2E617A7572652D646576696365732E6E657430820122300D06092A864886F70D01010105000382010F003082010A0282010100C2F6BC63A01CAAA1C2DDC8A5ABDFAC6EACB1D2B23F15B23A6E08560B7545C2362EBC80C7A4554D56531D3F48D5276F57526F2B2881A486C80EABD6C23C97334D36FA0F7F1DDEBC84394524F4D350CB96A924C05C761A4C3F16FD2635522884EC449230FB99ABF1E2CF205E392308A9D80CF978350383E1056C9D7D550285A788"

OK

+UUSORD: 0,2408
AT+USORD=0,512

+USORD: 0,512,"DB0EA83E7133E9B7E0DCBA3543EEE64CF2C3A779DF5346CB7038BDCEED4FCF1A8778AC9895FBED182129A2C992F80FD9765B48CDA4C8B659AB66D619250BA14374195530F082E3DA7ADB71347062804272CCD66C6FF22FA06BB570AD3772489322DFCBAC446D00A1BE6C14BCF851A35B060F176588739890CA0566794FA19B9B0203010001A38204B6308204B2308201F4060A2B06010401D679020402048201E4048201E001DE007600BBD9DFBC1F8A71B593942397AA927B473857950AAB52E81A909664368E1ED185000001697CB415ED000004030047304502205A2419DF07DB7B86DC94864C459F115ADD1FB4EA58B91D4D565E4D10AB720C28022100F41D50F070402CCF45EFCB685B78DFD6516A1A52FBD4A0D7C1EB22D27352C5CF007500A4B90990B418581487BB13A2CC67700A3C359804F91BDFB8E377CD0EC80DDC10000001697CB415F4000004030046304402207F42E26BE6EC17F6C734CDBB7461AFFE20DB868CD691A84E9C3095BBA9892F9302200F54C547085587DC187DA3955C406189CC634214EB1C015483756F3888DA4B470076004494652EB0EECEAFC44007D8A8FE28C0DAE682BED8CB31B53FD33396B5B681A8000001697CB4161B0000040300473045022100B59FCD00550830F157885E7275C16963DDB3CFD09AA2666F5DD05EEA000D463F022006E092839065EA24AAE16ED36ECD9B7B6FF1"

OK

+UUSORD: 0,3227
AT+USORD=0,512

+USORD: 0,512,"443C5C83FA309C4364F7F33BC4E80075005581D4C2169036014AEA0B9B573C53F0C0E43878702508172FA3AA1D0713D30C000001697CB415A1000004030046304402202CE32A904FCB06069C79366520C57D13D31842211E5187A8B625960F20449DF502207ABB05A2A9BB45F8141A62ECD1AAFE8CE22803E13A89C9FC1D6A32851116B0F8302706092B060104018237150A041A3018300A06082B06010505070302300A06082B06010505070301303E06092B06010401823715070431302F06272B060104018237150887DA867583EED90182C9851B81B59E6185F4EB60815D84D2DF4282E7937A02016402011D30818506082B0601050507010104793077305106082B060105050730028645687474703A2F2F7777772E6D6963726F736F66742E636F6D2F706B692F6D73636F72702F4D6963726F736F66742532304954253230544C532532304341253230322E637274302206082B060105050730018616687474703A2F2F6F6373702E6D736F6373702E636F6D301D0603551D0E04160414F486CA6FDCF24C667782CE9662A06958A1A1C764300B0603551D0F0404030204B0305D0603551D110456305482132A2E617A7572652D646576696365732E6E6574821A2A2E616D717077732E617A7572652D646576696365732E6E657482212A2E73752E6D616E6167656D656E742D617A7572652D646576696365732E6E65"

OK

+UUSORD: 0,2715
AT+USORD=0,512

+USORD: 0,512,"743081AC0603551D1F0481A43081A130819EA0819BA08198864B687474703A2F2F6D7363726C2E6D6963726F736F66742E636F6D2F706B692F6D73636F72702F63726C2F4D6963726F736F66742532304954253230544C532532304341253230322E63726C8649687474703A2F2F63726C2E6D6963726F736F66742E636F6D2F706B692F6D73636F72702F63726C2F4D6963726F736F66742532304954253230544C532532304341253230322E63726C304D0603551D2004463044304206092B0601040182372A013035303306082B060105050702011627687474703A2F2F7777772E6D6963726F736F66742E636F6D2F706B692F6D73636F72702F637073301F0603551D23041830168014919E3B446C3D579C42772A34D74FD1CC4A972CDA301D0603551D250416301406082B0601050507030206082B06010505070301300D06092A864886F70D01010B050003820201006683091669BD2B4C48BE50A94227C8CE8F229E2043E5132FE97A1D267D42A7AEE28E58DB66F0DEA8811F9187F9A6A58BFB6B7EAB0EAA6F75119448E493F11FC0EAAC1117EA553BB1F7458FA6CB4DE70AE695E924B8BB3E2E523B7DC3D07F0AD1E2B70CC257B7D273270BC767BBD02ED41227113153512BBD72A815BB044A1A6F2E973F5FCFCA170DDAB7338AF294BB2AF3DF027F79C9BFF00AABB4D38C61F8A6C489F0548DEC79713CECD21F6C"

OK

+UUSORD: 0,2203
AT+USORD=0,512

+USORD: 0,512,"4F94843FE50819915A91DF35FE7E1CEF4A554E439C30AA85DDE570306C446B99596F955F58A77F63DCFB151B95D418D26383B36ACE99BF363440D1A6E66F638340E567B6F625644212EB5A5D522BB2D56DA96E2BD9D505395937DD58860D08F2312D22DE4B20427CA000A1ED7296B9559CFCB73BFCA0243AE66582A2B7E670EB4506B8741FF66DC471EAD89F481BF6143AEFD9914D9398BDCFFED092A770DF3FB656649A6B5F4FB267A5AFF80264F9B4080C5D3EE9E66D2D9643A7262440BCE47DA1B67BA585A209306FB40B7B1F85C4F12F99C529688471131EFE2D5CC5474B7D1D968795CF317EB048157DF2A8691B5A428CEF260CE03D51D3A0EA4A46053F7B7305C61C6612E659884892CA4C677D8CB082585B82CF56A3C8BEA435000CCFCC8F018377243FF3C7CF8F5633FFDD01AEF27BF53C538DA25426C59A5A925F5A8DCF37090790B766A2520AAD8CC8386E0A7D5A0005B8308205B43082049CA00302010202100F2C10C95B06C0937FB8D449F83E8569300D06092A864886F70D01010B0500305A310B300906035504061302494531123010060355040A130942616C74696D6F726531133011060355040B130A43796265725472757374312230200603550403131942616C74696D6F7265204379626572547275737420526F6F74301E170D3136303532303132353135375A170D3234303532303132353135375A"

OK

+UUSORD: 0,1691
AT+USORD=0,512

+USORD: 0,512,"30818B310B3009060355040613025553311330110603550408130A57617368696E67746F6E3110300E060355040713075265646D6F6E64311E301C060355040A13154D6963726F736F667420436F72706F726174696F6E31153013060355040B130C4D6963726F736F6674204954311E301C060355040313154D6963726F736F667420495420544C53204341203230820222300D06092A864886F70D01010105000382020F003082020A02820201009EAA15C11BA1635FE65118C516BB11DC0B4D9B910ABA40492BDCD6060BC577592C3442450B4EA8C916F028F31F9695BF1ED39FCC87819621A4E7B33066AD7C6E0012AFBD2C3D45AEA03F75EC752005FC4162817CCC0ED921EE7300738315BA092FB160FDAA606D0B3F1A26593428B44244145B3C349D3526552350D26CFAA42BBDE43BF558CB0B1B23C67DD37DCC3DD0FD0103C89EBDE50823448C580350D413EE78B62DA4EABD3270A150624C96C19DB91C3D61DA462DDE8BD6F39BC5EB2EED8D3A9411C2DB80A50207CD7FF79E6174B2EC6C577A7FDA363E453CC6E39CDD4F9B51E76FBFA49BB6F1A304465E1721FCFC269087396C28C1F4F8E3CE16FFDB32A70B6AB3F0D55D6C395D5B9785BDBE2DB6EFC9E26E5CC86C41EDEE737CF3CA7828D230A8271768685BB52E2D8E7DCD288EAFD5DD97472C48BC22438E0A19D3DCC5DFD3F2A1EF76B1246291987BC67B38B5"

OK

+UUSORD: 0,1179
AT+USORD=0,512

+USORD: 0,512,"0110F010ACE28E4D052C7C53112C832CCD4AC9161845AAB088EDFBBF80D6C9030D9BFA936A3C5421CD6D32C5292EDDEF6C0C23812BA7356C04889CC5A1B67B3B8C041BAA4E1C48889F86F737E83FD9718A6FFDAEF240C5B8779EE8C0D5525F90E613248A23100602C51DD08C4A0675AA4998195EF7B01FA84067C2826CBB6C1ABFC87DBFEA680CBE21E9D473454C58D431F2A5C1655C6A07BBF44442014BAB620DDF4FC08502CDF743E3F534F645010203010001A38201423082013E301D0603551D0E04160414919E3B446C3D579C42772A34D74FD1CC4A972CDA301F0603551D23041830168014E59D5930824758CCACFA085436867B3AB5044DF030120603551D130101FF040830060101FF020100300E0603551D0F0101FF04040302018630270603551D250420301E06082B0601050507030106082B0601050507030206082B06010505070309303406082B0601050507010104283026302406082B060105050730018618687474703A2F2F6F6373702E64696769636572742E636F6D303A0603551D1F04333031302FA02DA02B8629687474703A2F2F63726C332E64696769636572742E636F6D2F4F6D6E69726F6F74323032352E63726C303D0603551D200436303430320604551D2000302A302806082B06010505070201161C68747470733A2F2F7777772E64696769636572742E636F6D2F435053300D06092A86"

OK

+UUSORD: 0,667
AT+USORD=0,512

+USORD: 0,512,"4886F70D01010B050003820101006C7FEA6A6FCF6B5BC134ACFFDC0EE07D8B1317E02F4E590EC403B9F405296547AE199AE854F664D5D8BD06E07122197BCE9ADD798BDF70274868DBF76F3319B565EB9F9007CCB847397D0F5113910D80D476502B8507606D6D599A294016C6C70DE06A574B8009BFEFC74B4557B394AED7D2740C0F0183E968F1E90297876AD86D66D56B02BC5048A0B2237789DE08B946A314F68C0E37963D89A50FD23242E42F2F435E3FC91DDB2A243479A207228F85485FC57E6D50F4342C3B9106BA525ABD668D230C4AB56ADE3349E1F8995D8F30CDCBC085C1036C68E6C75AD5C9D4589A373EAE2E32070B7B4B7E7C2BADDFC34C91397C1746AB7E5B296AA515554A2F0C0001690300186104466ED78FE358AE20A58D24CFC6625DCE1E3BA41085E002A822608500DE014E7E35761344EFA233E68214768ABE881B9E8D1A77390959EBFA69B3EF2515DB1A4F6709FD92973ABE1CCF0274189DE70F5BD5A0DD608BB62F627456CAE514C16E1602010100001AEDE774CA39E0AAF292F882472D47D34686EFCC2E2C54C3DE7021DC6A602B25E3C6F2F315DB78EAC1CBC4999C310ADC77A207913B47D7ABA62FAD4F3271AFC21078B4E5C5DCDDB5FE9DA8195C36DB53E5E4677B6A00D35A02D69F63D1796713E7405FBB5041DFDBDFFA0116455196171D8585E49DAF40D6041D981547AAB1A04C8BD12F"

OK

+UUSORD: 0,155
.-2
```

**Comment by sandeepmistry** [comment] 2019-03-27 19:04
Thanks @l0gicforce!

```
AT+CCLK?

+CCLK: "04/01/01,00:03:15+00"

OK
```

The problem is most likely cellular module is returning a time from the past, so the sketch on the board can't validate the servers certificate. I'm going to try to get another SIM to reproduce the issue (cc/ @gvarisco) - hopefully there's something in the MKRGSM library that can be done to configure the module to return the correct epoch time accurately with all SIMs.

As for a super short term workaround to unblock you, you can try to change the `getTime()` function in the sketch to return a hard coded value from https://www.epochconverter.com 

**NOTE the suggested workaround from above is not recommended for production use!!!**

**Comment by l0gicforce** [comment] 2019-03-29 08:06
Hi @sandeepmistry,

I can confirm the problem was indeed the network time.
The workaround using the hard coded timestamp works.

For now I just added the NTP time from: https://www.arduino.cc/en/Tutorial/MKRGSMExamplesGPRSUdpNtp

https://github.com/l0gicforce/ArduinoCloudProviderExamples/commit/af70b44c4beda40194e36746fe5462e65fc32d07

Thanks a lot!

```
Attempting to connect to the cellular network
.You're connected to the cellular network

Attempting to MQTT broker: IoTHubTestKB001.azure-devices.net 
Retrieving time from NTP
packet received
Seconds since Jan 1 1900 = 3762835388
Unix time = 1553846588
The UTC time is 8:03:08

You're connected to the MQTT broker

Publishing message
Publishing message
Publishing message
Publishing message
Publishing message

```

**Comment by sandeepmistry** [comment] 2019-03-29 14:23
Hi @l0gicforce,

Thanks for trying my suggestion, I'm glad to hear you were able to get things working!

I'll leave this issue open for now, so others can find it. Hopefully we can find a fix in the MKRGSM lib in the coming weeks.

**Comment by attie44** [comment] 2019-11-08 09:44
Hi @sandeepmistry and @l0gicforce

Has anyone found a solution to this issue?

**Comment by sandeepmistry** [comment] 2019-11-11 21:06
Hi @attie44,

Did you try @l0gicforce's suggestion in https://github.com/arduino/ArduinoCloudProviderExamples/issues/3#issuecomment-477906711. We have no further updates on the topic apart from that now.

**Comment by NegativeKontakt** [comment] 2020-04-12 21:53
Hi is there any update on this? I had the same error as above, returning error code -2. As above I used the NTP time to resolve that issue, but now I get an error code of 5? Trying to work out what that could be.

**Comment by GLwan** [comment] 2020-05-23 17:16
There is a small error in the program "Azure iot WiFi": a question mark should be added as
username += "/?api-version=2018-06-30"; 
It works with my "Nano iot 33" by just adding this mark.

**Comment by GLwan** [comment] 2020-05-23 19:16
i have no problem to use this sketch  "Azure iot GSM"to let my MKR1400 work, by adding the question symbol as
username += "/?api-version=2018-06-30";

**Comment by SahithyaYadav** [comment] 2021-07-29 07:15
Hi,
I am registering MKRGSM 1400 with Azure IoT. The device registered successfully, after registering the device, when I am connecting the board to Azure IoT Hub with the examples provided in Arduino IDE.

Arduino IDE using **File -> Examples -> Arduino Cloud Provider Examples -> AzureIoTHub->Azure_IoT_Hub_GSM**.

 I am getting error -3(Connection refused: server unavailable). But after few hours(around 12 hours) I could able to communicate with the cloud without any error. what would be the reason for this kind of behavior? anyone facing the same issue? 

```text
+USORD: 0,91,"1403030001011603030050AB9F56C7E6C09842F3ECE857D9C77604C549C6E823AB6411918872C9864A0036EFB2A3E965CF2920D522500B109E29DCCDACA7D411E8F04723B50281522CC821533F28A4AF1ABF0A0359648CC35832D0"

OK
AT+USORD=0,512

+USORD: 0,0,""

OK
AT+USOWR=0,149,"1703030090532471CABDDE6818D1D2DDEE8AD8D785AFA7BE926AC9CEB5063F8D8A8082FCD5C6054DD278F1BB19FF4BBAE43781A180B6DC681C3910E1CCF7C9F08D72B583BD028AF6AEC84405F652AF28F8D8EF23B41A971B189B1DA235E5AD6F6435107862D5D63CBF107D95B34774FDDC962FE98A5DA468805C139200C29F3A1193305C92087A4F14026FA4EA76E6B451602FB321"
ERROR

+UUSOCL: 0
AT+USOCL=0
ERROR
.3
AT+USOCR=6
+USOCR: 0
```

**Comment by per1234** [comment] 2023-10-30 19:37
Closing as off topic since the fault was not caused by any defect in the code hosted in this repository.

**Closed as not planned by per1234** 2023-10-30 19:37 UTC
Labels: bug, invalid
