### ISSUE TITLE
Google Cloud IOT Core Fails to connect

### ISSUE THREAD

**Issue by fabltd** [arduino/ArduinoCloudProviderExamples#9] opened 2019-11-19 17:09 UTC
Hi 

Have followed this example:

https://create.arduino.cc/projecthub/Arduino_Genuino/securely-connecting-a-mkr-gsm-1400-to-google-cloud-iot-core-b8b628

But it just keeps waiting at: Attempting to connect to MQTT Broker.

JT

**Comment by zjbarg** [comment] 2019-12-16 21:30
Solved?

**Comment by fabltd** [comment] 2021-07-21 17:36
Was.

The problem has happened again. Refuses to connect. Its been working fine and on the 9th of June it stopped and no more. Not sure what changed.

**Comment by adham995** [comment] 2021-07-23 23:25
same problem.

Not sure what changed ??

**Comment by adham995** [comment] 2021-07-24 11:23
@fabltd 
today the problem has solved and all it's okay.
Not sure what changed in GCP.

**Comment by netskink** [comment] 2021-08-11 02:35
Hmm. Its working for you now?

**Comment by adham995** [comment] 2021-08-21 13:18
> Hmm. Its working for you now?

The problem again ???
Today not working ....

I think the problem from google cloud platform!!!

**Comment by netskink** [comment] 2021-08-21 14:04
@adham995 are you having problems now?

**Comment by adham995** [comment] 2021-08-21 15:00
> @adham995 are you having problems now?

Yes!!

**Comment by netskink** [comment] 2021-08-21 15:16
Hmm, but it worked before? Have you seen my work here? https://github.com/netskink/ssl_publy

**Comment by adham995** [comment] 2021-08-21 16:33
> Hmm, but it worked before? Have you seen my work here? https://github.com/netskink/ssl_publy

Yes, it worked before.
It works for long time and some days not working, so the problem not related with software/programming the problem from cloud platform.

**Comment by netskink** [comment] 2021-08-21 20:40
Hmm.  I have yet to get it working.  I stopped work on the project but my pal said he got it working using the GCP sample.  Rather than work on the problem directly, I have been learning SSL/TLS and certificates.  If I get a solution, I'll post it.  Please keep me posted.

**Comment by netskink** [comment] 2021-08-31 14:29
I got this working.  My method was shown on the github repo I provided above.

**Comment by adham995** [comment] 2021-09-03 16:41
> I got this working.  My method was shown on the github repo I provided above.

I will use your method. Any way I'm using the HTTP protocol and it works with out interruption.

**Comment by netskink** [comment] 2021-09-03 17:08
Very good.  I have a discussion section open on my repo.  Feel free to ask questions there.  I plan to edit that repo for clarity.

**Comment by per1234** [comment] 2023-10-30 19:25
Thanks for your report @fabltd 
> the problem not related with software/programming the problem from cloud platform.

Since you have determined that the fault is not caused by the code hosted in this repository, I will close this as off topic.

**Closed as not planned by per1234** 2023-10-30 19:25 UTC
Labels: bug, invalid
